// ── CITY & LIGHT — Data Config ──
// Données embarquées + Supabase en fallback

const SUPA_URL = 'https://pyukliuxknbsodsxdbpx.supabase.co';
const SUPA_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5dWtsaXV4a25ic29kc3hkYnB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ4NzcxNjAsImV4cCI6MjA5MDQ1MzE2MH0.vOlkPzdru8CL45b0zCauiCj8W_29W6dRXLXKCAtWmWU';

// ── DONNÉES EMBARQUÉES (toujours disponibles) ──
const DB = [
{
"id": "guerlain-paris",
"name": "Guerlain Paris",
"badge": "Parfumerie · Paris 8e",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "68 avenue des Champs-Élysées, 75008 Paris",
"phone": "+33 1 45 62 52 57",
"website": "https://www.guerlain.com",
"hours": "Lun–Sam 10h–20h",
"category": "Parfumerie",
"desc_fr": "La maison Guerlain, fondée en 1828, incarne l'excellence de la parfumerie française depuis près de deux siècles.",
"lat": 48.8698,
"lon": 2.3078,
"main_photo": "https://static.wixstatic.com/media/631e74_6212fb2a514d42c5b9222ee482cc1f5b~mv2.jpg",
"photos": []
},
{
"id": "louis-vuitton-paris",
"name": "Louis Vuitton Paris",
"badge": "Maroquinerie · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "101 avenue des Champs-Élysées, 75008 Paris",
"phone": "",
"website": "https://www.louisvuitton.com",
"hours": "Lun–Dim 10h–20h",
"category": "Maroquinerie",
"desc_fr": "Le flagship Louis Vuitton des Champs-Élysées est l'une des boutiques les plus visitées au monde.",
"lat": 48.8736,
"lon": 2.3006,
"main_photo": "https://static.wixstatic.com/media/631e74_a0f529f3d56f4d108261bd78b2f214dd~mv2.jpg",
"photos": []
},
{
"id": "dior-paris",
"name": "Dior Paris",
"badge": "Haute Couture · Paris 8e",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "30 avenue Montaigne, 75008 Paris",
"phone": "",
"website": "https://www.dior.com",
"hours": "Lun–Sam 10h–19h",
"category": "Haute Couture",
"desc_fr": "La maison Dior, fondée en 1946, a établi son adresse mythique au 30 avenue Montaigne.",
"lat": 48.8656,
"lon": 2.3017,
"main_photo": "https://static.wixstatic.com/media/631e74_78f9d28f6f59492d84e0c98cc1b637a6~mv2.jpg",
"photos": []
},
{
"id": "paxton-whitfield",
"name": "Paxton & Whitfield",
"badge": "Fromagerie · Londres",
"city": "Londres",
"country": "UK",
"region": "europe",
"address": "93 Jermyn St, London SW1Y 6JE",
"phone": "+44 20 7930 0259",
"website": "https://www.paxtonandwhitfield.co.uk",
"hours": "Lun–Sam 9h30–18h",
"category": "Fromagerie Fine",
"desc_fr": "Fondée en 1797, Paxton & Whitfield est la plus ancienne fromagerie fine de Londres.",
"lat": 51.5074,
"lon": -0.1376,
"main_photo": "https://static.wixstatic.com/media/631e74_1cd1d0d4339e499ca5170614889ff684~mv2.jpg",
"photos": []
},
{
"id": "floris-89",
"name": "Floris 89",
"badge": "Parfumerie · Londres",
"city": "Londres",
"country": "UK",
"region": "europe",
"address": "89 Jermyn St, London SW1Y 6JH",
"phone": "+44 20 7930 2885",
"website": "https://www.florislondon.com",
"hours": "Lun–Sam 9h30–18h",
"category": "Parfumerie",
"desc_fr": "Floris est la plus ancienne parfumerie de Londres, fondée en 1730.",
"lat": 51.5068,
"lon": -0.1386,
"main_photo": "https://static.wixstatic.com/media/631e74_3bd5447b449845dca7702622a119d194~mv2.jpg",
"photos": []
},
{
"id": "valextra",
"name": "Valextra Milan",
"badge": "Maroquinerie · Milan",
"city": "Milan",
"country": "Italie",
"region": "europe",
"address": "Via Manzoni 3, 20121 Milano",
"phone": "",
"website": "https://www.valextra.com",
"hours": "Lun–Sam 10h–19h",
"category": "Maroquinerie",
"desc_fr": "Valextra est la maison milanaise de maroquinerie d'exception, fondée en 1937.",
"lat": 45.4722,
"lon": 9.1896,
"main_photo": "https://static.wixstatic.com/media/631e74_7e9297adf6dc4fe6ba75c075831b0d35~mv2.jpg",
"photos": []
},
{
"id": "nuir-vintage",
"name": "Nuir Vintage",
"badge": "Mode Vintage · Tokyo",
"city": "Tokyo",
"country": "Japon",
"region": "asie",
"address": "Shibuya, Tokyo",
"phone": "",
"website": "",
"hours": "",
"category": "Mode Vintage",
"desc_fr": "Nuir Vintage est l'une des boutiques vintage les plus sélectives de Shibuya.",
"lat": 35.6595,
"lon": 139.7004,
"main_photo": "",
"photos": []
},
{
"id": "mandarake",
"name": "Mandarake",
"badge": "Culture · Tokyo",
"city": "Tokyo",
"country": "Japon",
"region": "asie",
"address": "Shibuya, Tokyo",
"phone": "",
"website": "https://www.mandarake.co.jp",
"hours": "12h–20h",
"category": "Culture & Manga",
"desc_fr": "Mandarake est le temple de la culture pop japonaise à Shibuya.",
"lat": 35.6614,
"lon": 139.6982,
"main_photo": "",
"photos": []
},
{
"id": "barovier-toso",
"name": "Barovier&Toso",
"badge": "Art du Verre · Venise",
"city": "Venise",
"country": "Italie",
"region": "europe",
"address": "Fondamenta Vetrai 28, Murano",
"phone": "",
"website": "https://www.barovieretoso.com",
"hours": "Lun–Sam 9h–17h",
"category": "Art du Verre",
"desc_fr": "Barovier & Toso est la plus ancienne entreprise familiale au monde, fondée en 1295.",
"lat": 45.4408,
"lon": 12.3155,
"main_photo": "",
"photos": []
},
{
"id": "merchant-of-venice",
"name": "The Merchant of Venice",
"badge": "Parfumerie · Venise",
"city": "Venise",
"country": "Italie",
"region": "europe",
"address": "Calle del Ridotto, San Marco, Venezia",
"phone": "",
"website": "https://www.themerchantofvenice.com",
"hours": "Lun–Dim 10h–19h",
"category": "Parfumerie",
"desc_fr": "The Merchant of Venice perpétue la tradition des parfumeurs vénitiens du XVIe siècle.",
"lat": 45.438,
"lon": 12.3358,
"main_photo": "",
"photos": []
},
{
"id": "33-rue-majorelle",
"name": "33 rue Majorelle",
"badge": "Art & Design · Marrakech",
"city": "Marrakech",
"country": "Maroc",
"region": "afrique",
"address": "33 rue Majorelle, Guéliz, Marrakech",
"phone": "",
"website": "",
"hours": "Lun–Dim 9h–19h",
"category": "Art & Design",
"desc_fr": "33 rue Majorelle est une galerie boutique au cœur de Marrakech.",
"lat": 31.6372,
"lon": -7.9904,
"main_photo": "",
"photos": []
},
{
"id": "pop-international-galleries",
"name": "Pop International Galleries",
"badge": "Art · New York",
"city": "New York",
"country": "USA",
"region": "ameriques",
"address": "473 W Broadway, New York, NY 10012",
"phone": "",
"website": "",
"hours": "Mar–Dim 11h–19h",
"category": "Galerie d'Art",
"desc_fr": "Pop International Galleries est l'une des galeries d'art pop les plus reconnues de New York.",
"lat": 40.7224,
"lon": -74.003,
"main_photo": "",
"photos": []
},
{
"id": "dinosaur-designs",
"name": "Dinosaur Designs",
"badge": "Design · Sydney",
"city": "Sydney",
"country": "Australie",
"region": "oceanie",
"address": "Strand Arcade, Sydney NSW 2000",
"phone": "",
"website": "https://www.dinosaurdesigns.com.au",
"hours": "Lun–Sam 9h–18h",
"category": "Design & Bijoux",
"desc_fr": "Dinosaur Designs est une maison de design australienne iconique, fondée en 1985.",
"lat": -33.8897,
"lon": 151.1994,
"main_photo": "",
"photos": []
},
{
"id": "galerie-neel",
"name": "Galerie Neel",
"badge": "Art · Cannes",
"city": "Cannes",
"country": "France",
"region": "europe",
"address": "3 Rue du Commandant Vidal, 06400 Cannes",
"phone": "",
"website": "https://www.galerieneel.com",
"hours": "Mar–Sam 10h–19h",
"category": "Galerie d'Art",
"desc_fr": "La Galerie Neel, entreprise familiale d'artistes ouverte depuis 1992.",
"lat": 43.5516,
"lon": 7.0174,
"main_photo": "",
"photos": []
},
{
"id": "cedric-grolet",
"name": "Cedric Grolet - Airelles",
"badge": "Pâtisserie · Saint-Tropez",
"city": "Saint-Tropez",
"country": "France",
"region": "europe",
"address": "Hôtel Airelles, Saint-Tropez 83990",
"phone": "",
"website": "",
"hours": "Saisonnier",
"category": "Pâtisserie",
"desc_fr": "Le chef pâtissier Cédric Grolet, sacré meilleur chef pâtissier du monde.",
"lat": 43.2727,
"lon": 6.6407,
"main_photo": "",
"photos": []
},
{
"id": "casa-bloom",
"name": "Casa Bloom",
"badge": "Mode · Barcelone",
"city": "Barcelone",
"country": "Espagne",
"region": "europe",
"address": "Barcelone, Espagne",
"phone": "",
"website": "",
"hours": "",
"category": "Mode",
"desc_fr": "Casa Bloom est une boutique de mode indépendante au cœur de Barcelone.",
"lat": 41.3851,
"lon": 2.1734,
"main_photo": "https://pyukliuxknbsodsxdbpx.supabase.co/storage/v1/object/public/boutiques-photos/casa-bloom/Casa%20Bloom%20-%201.jpg",
"photos": [
"https://pyukliuxknbsodsxdbpx.supabase.co/storage/v1/object/public/boutiques-photos/casa-bloom/Casa%20Bloom%20-%201.jpg",
"https://pyukliuxknbsodsxdbpx.supabase.co/storage/v1/object/public/boutiques-photos/casa-bloom/Casa%20Bloom%20-%202.jpg",
"https://pyukliuxknbsodsxdbpx.supabase.co/storage/v1/object/public/boutiques-photos/casa-bloom/Casa%20Bloom%20-%203.jpg"
]
},
{
"id": "ale-paris-luxury-vintage-boutique",
"name": "ALE Paris - Luxury Vintage Boutique",
"badge": "Mode Vintage · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8666, \"longitude\": 2.3431}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"6\", \"name\": \"Pass. du Grand Cerf\", \"apt\": \"\"}, \"formatted\": \"6 Pass. du Grand Cerf, 75002 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75002\", \"subdivision\": \"IDF\"}",
"phone": "",
"website": "",
"hours": "Ferme à 19:00",
"category": "Mode Vintage",
"desc_fr": "",
"desc_en": "",
"lat": 48.8666,
"lon": 2.3431,
"main_photo": "",
"photos": [],
"status": "published"
},
{
"id": "opulence-vintage",
"name": "Opulence Vintage",
"badge": "Mode Vintage · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8666, \"longitude\": 2.3431}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"107\", \"name\": \"Rue Réaumur\", \"apt\": \"\"}, \"formatted\": \"107 Rue Réaumur, 75002 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75002\", \"subdivision\": \"IDF\"}",
"phone": "06 48 91 79 86",
"website": "",
"hours": "Lun 13:00-19:00",
"category": "Mode Vintage",
"desc_fr": "",
"desc_en": "",
"lat": 48.8666,
"lon": 2.3431,
"main_photo": "https://lh3.googleusercontent.com/p/AF1QipOQ2nCDEfmru64pah9i-W-u6hj3JSxwFowUSqvl=w203-h152-k-no",
"photos": [
"https://lh3.googleusercontent.com/p/AF1QipOQ2nCDEfmru64pah9i-W-u6hj3JSxwFowUSqvl=w203-h152-k-no"
],
"status": "published"
},
{
"id": "passion-luxe-depot-vente-de-luxe",
"name": "Passion Luxe - Dépôt vente de luxe",
"badge": "Mode Vintage · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8541, \"longitude\": 2.3566}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"11\", \"name\": \"Rue du Roi de Sicile\", \"apt\": \"\"}, \"formatted\": \"11 Rue du Roi de Sicile, 75004 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75004\", \"subdivision\": \"IDF\"}",
"phone": "01 73 75 32 18",
"website": "",
"hours": "Ferme à 19:00",
"category": "Mode Vintage",
"desc_fr": "",
"desc_en": "",
"lat": 48.8541,
"lon": 2.3566,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAweoF6trsdyZYpediDGnnhGN_YxvbF-5BH6KqRFsXUZ-ajf3NRk2qujr7MhF3v5Z1ZFtftDV9hjYtBbh7KgK_ap2oIfF_kJDCKHtQWedDbGnwiunw1kXyXKsLZHaw96K535em8e57=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAweoF6trsdyZYpediDGnnhGN_YxvbF-5BH6KqRFsXUZ-ajf3NRk2qujr7MhF3v5Z1ZFtftDV9hjYtBbh7KgK_ap2oIfF_kJDCKHtQWedDbGnwiunw1kXyXKsLZHaw96K535em8e57=w800-h600-k-no"
],
"status": "published"
},
{
"id": "la-mode-vintage",
"name": "La Mode Vintage",
"badge": "Mode Vintage · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8592, \"longitude\": 2.3814}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"12\", \"name\": \"Rue Rochebrune\", \"apt\": \"\"}, \"formatted\": \"12 Rue Rochebrune, 75011 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75011\", \"subdivision\": \"IDF\"}",
"phone": "06 63 79 72 04",
"website": "",
"hours": "Ferme à 19:00",
"category": "Mode Vintage",
"desc_fr": "",
"desc_en": "",
"lat": 48.8592,
"lon": 2.3814,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAweqEHkaXzXPbeZvr_AUyr70BvsNMlONt_8XZ7lIdbeeu3c0DE61f3zmlKz-ml7zoTPNn_-UqdQhVklqmI_w-KfcWFLK4EGeYaNub-owlPgs9qwbaVhgqWk5LjFoC44RU1JDL_Etj=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAweqEHkaXzXPbeZvr_AUyr70BvsNMlONt_8XZ7lIdbeeu3c0DE61f3zmlKz-ml7zoTPNn_-UqdQhVklqmI_w-KfcWFLK4EGeYaNub-owlPgs9qwbaVhgqWk5LjFoC44RU1JDL_Etj=w800-h600-k-no"
],
"status": "published"
},
{
"id": "valois-vintage-paris",
"name": "VALOIS VINTAGE PARIS",
"badge": "Mode Vintage · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8752, \"longitude\": 2.3108}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"8\", \"name\": \"Rue des Saussaies\", \"apt\": \"\"}, \"formatted\": \"8 Rue des Saussaies, 75008 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75008\", \"subdivision\": \"IDF\"}",
"phone": "01 49 24 97 64",
"website": "https://www.valoisvintage.com",
"hours": "Lun-Sam 10:30-18:30",
"category": "Mode Vintage",
"desc_fr": "Valois Vintage Paris est l'une des adresses les plus réputées du dépôt-vente de luxe parisien. Installée rue des Saussaies, cette boutique confidentielle propose une sélection rigoureuse de pièces Hermès, Chanel, Louis Vuitton.",
"desc_en": "Valois Vintage Paris is one of the most reputable luxury consignment addresses in Paris. Located on Rue des Saussaies, this discreet boutique offers a rigorous selection of Hermès, Chanel, Louis Vuitton pieces.",
"lat": 48.8752,
"lon": 2.3108,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAwepU6a-PH_0-PEHrTiFyCQzYNPqQZuQ5kaJEeRYeA3eMLPGzRGqGonZGRrRTSsV9tMgDCxD1sOnICR6vzrSeyK7Gc55Elg4rVQS6HITKWPK97RKtW6VR7VxPtMSeQmwbA09KpieMJw=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAwepU6a-PH_0-PEHrTiFyCQzYNPqQZuQ5kaJEeRYeA3eMLPGzRGqGonZGRrRTSsV9tMgDCxD1sOnICR6vzrSeyK7Gc55Elg4rVQS6HITKWPK97RKtW6VR7VxPtMSeQmwbA09KpieMJw=w800-h600-k-no"
],
"status": "published"
},
{
"id": "palace-callas-vintage",
"name": "Palace Callas Vintage",
"badge": "Mode Vintage · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8541, \"longitude\": 2.3566}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"16\", \"name\": \"Rue du Pont Louis-Philippe\", \"apt\": \"\"}, \"formatted\": \"16 Rue du Pont Louis-Philippe, 75004 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75004\", \"subdivision\": \"IDF\"}",
"phone": "06 60 20 14 50",
"website": "",
"hours": "Lun 12:30-19:00",
"category": "Mode Vintage",
"desc_fr": "",
"desc_en": "",
"lat": 48.8541,
"lon": 2.3566,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAwepHlLAudQKHMoFoCtR2A53gOO2l0zjoQkEQTAOCx7Si6Z87iLlgXRYe22WWonP7ardNzBIxlzF9-cJE_g9IjN8Ik9JwgeGVxGFxfd1nkKe6aDX5dYWJ1pwjHpcx1t8piq-XoIA=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAwepHlLAudQKHMoFoCtR2A53gOO2l0zjoQkEQTAOCx7Si6Z87iLlgXRYe22WWonP7ardNzBIxlzF9-cJE_g9IjN8Ik9JwgeGVxGFxfd1nkKe6aDX5dYWJ1pwjHpcx1t8piq-XoIA=w800-h600-k-no"
],
"status": "published"
},
{
"id": "the-room-vintage-shop",
"name": "THE ROOM - Vintage Shop",
"badge": "Mode Vintage · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8541, \"longitude\": 2.3566}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"14\", \"name\": \"Rue des Écouffes\", \"apt\": \"\"}, \"formatted\": \"14 Rue des Écouffes, 75004 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75004\", \"subdivision\": \"IDF\"}",
"phone": "01 45 35 21 53",
"website": "",
"hours": "Ferme à 19:30",
"category": "Mode Vintage",
"desc_fr": "",
"desc_en": "",
"lat": 48.8541,
"lon": 2.3566,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAwerWiryQTnLbv2yu0LX6qnDsxdPsQEeDWBjo3IREelpGhpVqvJyLcNP1sp2vHzhAvBSDInkdGGAHireQyQxFW-vBi-Q4cjfAFRN1Igj8vrLJi9cyzNlWzJnv5LT6-pX4zig5xww=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAwerWiryQTnLbv2yu0LX6qnDsxdPsQEeDWBjo3IREelpGhpVqvJyLcNP1sp2vHzhAvBSDInkdGGAHireQyQxFW-vBi-Q4cjfAFRN1Igj8vrLJi9cyzNlWzJnv5LT6-pX4zig5xww=w800-h600-k-no"
],
"status": "published"
},
{
"id": "depot-vente-la-marelle",
"name": "Dépôt-vente La Marelle",
"badge": "Mode Vintage · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8666, \"longitude\": 2.3375}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"25\", \"name\": \"Galerie Vivienne\", \"apt\": \"\"}, \"formatted\": \"25 Galerie Vivienne, 75002 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75002\", \"subdivision\": \"IDF\"}",
"phone": "01 42 60 08 19",
"website": "https://lamarelle-galerievivienne.fr",
"hours": "Lun-Sam 10:30-18:30",
"category": "Mode Vintage",
"desc_fr": "Nichée au cœur de la Galerie Vivienne, La Marelle est une institution du dépôt-vente de luxe parisien depuis plus de 30 ans. Dans ce cadre architectural exceptionnel, on y trouve des pièces de créateurs soigneusement sélectionnées.",
"desc_en": "Nestled in the heart of the Galerie Vivienne, La Marelle is an institution of Parisian luxury consignment for over 30 years. In this exceptional architectural setting, you will find carefully selected designer pieces.",
"lat": 48.8666,
"lon": 2.3375,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAweoiWJZWlnRZbbETxMeLFBT2YZpfCAxaokg-WE1f2uP0x9QEehGCPQABpWA05zQKUgOeL5vtzwNnuDw15M5bVXk1QLxdbzUlvc8PsX07eSUAbs0Xv4w-cZFhzFwl08qPijbhKeWyhQ=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAweoiWJZWlnRZbbETxMeLFBT2YZpfCAxaokg-WE1f2uP0x9QEehGCPQABpWA05zQKUgOeL5vtzwNnuDw15M5bVXk1QLxdbzUlvc8PsX07eSUAbs0Xv4w-cZFhzFwl08qPijbhKeWyhQ=w800-h600-k-no"
],
"status": "published"
},
{
"id": "m82-turenne-depot-vente-luxe",
"name": "M82 Turenne - Dépôt vente luxe",
"badge": "Mode Vintage · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8625, \"longitude\": 2.3589}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"82\", \"name\": \"Rue de Turenne\", \"apt\": \"\"}, \"formatted\": \"82 Rue de Turenne, 75003 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75003\", \"subdivision\": \"IDF\"}",
"phone": "06 03 06 48 08",
"website": "",
"hours": "Ferme à 19:00",
"category": "Mode Vintage",
"desc_fr": "",
"desc_en": "",
"lat": 48.8625,
"lon": 2.3589,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAweq-7jFoR-_aklNrfC4rVqcJi_Us4sgrPuxUhNxX5sAZDaJm7JC95LobrhqMF697_seJDqmnE6Ra-yIbuK43s0PmyeKVGSWbAJ-vNDXGm8OtD023CHomzYMq22tcy9Ek3QwT4Z8q=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAweq-7jFoR-_aklNrfC4rVqcJi_Us4sgrPuxUhNxX5sAZDaJm7JC95LobrhqMF697_seJDqmnE6Ra-yIbuK43s0PmyeKVGSWbAJ-vNDXGm8OtD023CHomzYMq22tcy9Ek3QwT4Z8q=w800-h600-k-no"
],
"status": "published"
},
{
"id": "the-parisian-vintage",
"name": "The Parisian Vintage",
"badge": "Mode Vintage · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8625, \"longitude\": 2.3589}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"20\", \"name\": \"Rue Saint-Claude\", \"apt\": \"\"}, \"formatted\": \"20 Rue Saint-Claude, 75003 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75003\", \"subdivision\": \"IDF\"}",
"phone": "06 40 90 60 32",
"website": "https://www.theparisianvintage.com",
"hours": "Ferme à 19:00",
"category": "Mode Vintage",
"desc_fr": "The Parisian Vintage est une boutique de mode vintage pointue du Marais, proposant une sélection de pièces de designer des années 60 aux années 2000. Une curation exigeante pour des amateurs de mode éclairés.",
"desc_en": "The Parisian Vintage is a discerning vintage fashion boutique in the Marais, offering a selection of designer pieces from the 1960s to the 2000s. An exacting curation for enlightened fashion lovers.",
"lat": 48.8625,
"lon": 2.3589,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAweqT4LfioQHayhwg4MNln0syoiw99lb9KNv9AP1mavoMSFZSRTSn5S82HfKb41q9qYKYIDaSB2Naq8mEhCtRLkK5cMVaMu5ZXOffm-HZ061eIamx1dxEvR1Tlg6LS20zE0PoFPKTuA=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAweqT4LfioQHayhwg4MNln0syoiw99lb9KNv9AP1mavoMSFZSRTSn5S82HfKb41q9qYKYIDaSB2Naq8mEhCtRLkK5cMVaMu5ZXOffm-HZ061eIamx1dxEvR1Tlg6LS20zE0PoFPKTuA=w800-h600-k-no"
],
"status": "published"
},
{
"id": "cornerluxe-depot-vente-paris-16",
"name": "CORNERLUXE DEPOT VENTE PARIS 16",
"badge": "Dépôt-vente Luxe · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8638, \"longitude\": 2.2768}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"4\", \"name\": \"Av. Bugeaud\", \"apt\": \"\"}, \"formatted\": \"4 Av. Bugeaud, 75116 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75116\", \"subdivision\": \"IDF\"}",
"phone": "09 82 57 58 56",
"website": "",
"hours": "Mar-Sam 10:30-18:30",
"category": "Dépôt-vente Luxe",
"desc_fr": "",
"desc_en": "",
"lat": 48.8638,
"lon": 2.2768,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAweopYuegP5eeqj0BAHnNAheYVSghXKcKU6F7PHR84nfrXvtCfgRm_pVwnyabFlSV-ALPg6cTml1fN_5Q6vfYJwmNgj64lr9po36KjQQr14qlnPJGm9LuvMZrz0mUu9WVcoO_5JNh-Q=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAweopYuegP5eeqj0BAHnNAheYVSghXKcKU6F7PHR84nfrXvtCfgRm_pVwnyabFlSV-ALPg6cTml1fN_5Q6vfYJwmNgj64lr9po36KjQQr14qlnPJGm9LuvMZrz0mUu9WVcoO_5JNh-Q=w800-h600-k-no"
],
"status": "published"
},
{
"id": "old-fashioned-club",
"name": "Old Fashioned Club",
"badge": "Dépôt-vente Luxe · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8752, \"longitude\": 2.3108}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"4\", \"name\": \"Rue des Saussaies\", \"apt\": \"\"}, \"formatted\": \"4 Rue des Saussaies, 75008 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75008\", \"subdivision\": \"IDF\"}",
"phone": "06 83 09 50 01",
"website": "",
"hours": "Lun-Sam 11:00-19:00",
"category": "Dépôt-vente Luxe",
"desc_fr": "",
"desc_en": "",
"lat": 48.8752,
"lon": 2.3108,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAwep-k0Z8PfyqyKo5EcvEu-3y-ewdgeXUjnqUuR1S-G5oOY4xeTvFbIjTUtfZrNNsrFFhXAZpHX_TCQTD-M85oZAmc7mRZXB1LG7NYqX_1g_1iTX4xn5dfc_VlZg-dt5aPYFOixBI0QTGVjtk=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAwep-k0Z8PfyqyKo5EcvEu-3y-ewdgeXUjnqUuR1S-G5oOY4xeTvFbIjTUtfZrNNsrFFhXAZpHX_TCQTD-M85oZAmc7mRZXB1LG7NYqX_1g_1iTX4xn5dfc_VlZg-dt5aPYFOixBI0QTGVjtk=w800-h600-k-no"
],
"status": "published"
},
{
"id": "les-champs-d-or-horlogerie-de-luxe",
"name": "Les Champs d'Or - Horlogerie de luxe",
"badge": "Horlogerie & Bijoux · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.866, \"longitude\": 2.31}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"6\", \"name\": \"Av. Franklin Delano Roosevelt\", \"apt\": \"\"}, \"formatted\": \"6 Av. Franklin Delano Roosevelt, 75008 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75008\", \"subdivision\": \"IDF\"}",
"phone": "06 07 45 26 28",
"website": "https://www.leschampsedor.com",
"hours": "Lun-Sam 10:00-19:00",
"category": "Horlogerie & Bijoux",
"desc_fr": "Les Champs d'Or est une horlogerie-bijouterie de luxe avenue Franklin Roosevelt, spécialisée dans la vente et l'expertise de montres et bijoux de grandes maisons. Un écrin de prestige au cœur du Triangle d'Or.",
"desc_en": "Les Champs d'Or is a luxury watchmaking and jewellery shop on Avenue Franklin Roosevelt, specialising in the sale and expertise of watches and jewellery from great houses. A prestigious setting in the heart of the Golden Triangle.",
"lat": 48.866,
"lon": 2.31,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAweq2M5cz01WgEqzVdWCoZBW-Bw-XTvgbcqr7jsf_XQZTJlXHBgEU1yQnqt11MpK0NRMahwhYklEgImvet3cejiBiUlqSbzNaLhWLUPw0JLMV37i0ukzGt7aUzVZJ9DVYvYkO06Th=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAweq2M5cz01WgEqzVdWCoZBW-Bw-XTvgbcqr7jsf_XQZTJlXHBgEU1yQnqt11MpK0NRMahwhYklEgImvet3cejiBiUlqSbzNaLhWLUPw0JLMV37i0ukzGt7aUzVZJ9DVYvYkO06Th=w800-h600-k-no"
],
"status": "published"
},
{
"id": "serge-lutens",
"name": "Serge Lutens",
"badge": "Parfumerie · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.864, \"longitude\": 2.337}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"142\", \"name\": \"Galerie de Valois\", \"apt\": \"\"}, \"formatted\": \"142 Galerie de Valois, 75001 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75001\", \"subdivision\": \"IDF\"}",
"phone": "01 49 27 09 09",
"website": "https://www.sergelutens.com",
"hours": "Lun-Sam 11:00-19:00",
"category": "Parfumerie",
"desc_fr": "Serge Lutens est une maison de parfumerie d'auteur installée au Palais Royal depuis 1992. Dans cet écrin précieux de la Galerie de Valois, le parfumeur visionnaire propose des créations olfactives uniques, loin des codes commerciaux.",
"desc_en": "Serge Lutens is an author's perfumery house installed at the Palais Royal since 1992. In this precious setting in the Galerie de Valois, the visionary perfumer offers unique olfactory creations, far from commercial codes.",
"lat": 48.864,
"lon": 2.337,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAwerMuKiW8zY39fNduiry0RQmo3mISbZR4yrOIgfKjoFKz66PGwTVVvH_AxRg2KUsmBSofIAUWQLw46swZ2qMyD0fHjUDJ2ZhRlYoSxtaqaMZmInHJDH4kp46mltvx_CFcwrB218eKrRe7TBF=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAwerMuKiW8zY39fNduiry0RQmo3mISbZR4yrOIgfKjoFKz66PGwTVVvH_AxRg2KUsmBSofIAUWQLw46swZ2qMyD0fHjUDJ2ZhRlYoSxtaqaMZmInHJDH4kp46mltvx_CFcwrB218eKrRe7TBF=w800-h600-k-no"
],
"status": "published"
},
{
"id": "foie-gras-luxe-foie-gras-et-co",
"name": "Foie Gras Luxe - Foie Gras & Co",
"badge": "Épicerie Fine · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.862, \"longitude\": 2.347}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"26\", \"name\": \"Rue Montmartre\", \"apt\": \"\"}, \"formatted\": \"26 Rue Montmartre, 75001 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75001\", \"subdivision\": \"IDF\"}",
"phone": "01 42 36 14 73",
"website": "",
"hours": "Lun-Sam 10:00-19:00",
"category": "Épicerie Fine",
"desc_fr": "",
"desc_en": "",
"lat": 48.862,
"lon": 2.347,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAwerWhdbLKW_PtmBocFBtCv1-gqo7tLF81mBbYDR5hXE-9uQavscMzDWaNyITX1yuflJCh_iahXC06ZSU628-pMwdMmAbbpvO_sLvaGTFkHKjUgAEyK1gG-FUak9ppUBowWfFOfXaQw=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAwerWhdbLKW_PtmBocFBtCv1-gqo7tLF81mBbYDR5hXE-9uQavscMzDWaNyITX1yuflJCh_iahXC06ZSU628-pMwdMmAbbpvO_sLvaGTFkHKjUgAEyK1gG-FUak9ppUBowWfFOfXaQw=w800-h600-k-no"
],
"status": "published"
},
{
"id": "les-rituelles-lingerie",
"name": "Les Rituelles Lingerie",
"badge": "Lingerie Fine · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8846, \"longitude\": 2.337}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"6\", \"name\": \"Rue Houdon\", \"apt\": \"\"}, \"formatted\": \"6 Rue Houdon, 75018 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75018\", \"subdivision\": \"IDF\"}",
"phone": "01 77 16 57 29",
"website": "https://lesrituelles.fr",
"hours": "Mar-Sam 11:00-19:00",
"category": "Lingerie Fine",
"desc_fr": "Les Rituelles est une boutique de lingerie fine installée rue Houdon à Montmartre. Une sélection pointue de créateurs de lingerie française et européenne, dans un cadre intime et chaleureux qui invite à prendre soin de soi.",
"desc_en": "Les Rituelles is a fine lingerie boutique on Rue Houdon in Montmartre. A carefully selected range of French and European lingerie designers, in an intimate and warm setting that invites self-care.",
"lat": 48.8846,
"lon": 2.337,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAweoJ4SJHTSxKkJwBgIVmGQnAhz_cFBVqnB4bX0cE29HxXkpb473_EF-QuZzGYZ7xNHf8l4V7vYEAGqXc9yU3fBKtZsKS2AkiyjeJfwchmHWmJz-m3fATbR8ME8TPhgp6T3qgYzgI=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAweoJ4SJHTSxKkJwBgIVmGQnAhz_cFBVqnB4bX0cE29HxXkpb473_EF-QuZzGYZ7xNHf8l4V7vYEAGqXc9yU3fBKtZsKS2AkiyjeJfwchmHWmJz-m3fATbR8ME8TPhgp6T3qgYzgI=w800-h600-k-no"
],
"status": "published"
},
{
"id": "miller-bijouterie-bijoux-et-montres-d-occasio",
"name": "Miller Bijouterie - Bijoux et montres d'occasion",
"badge": "Bijoux Vintage · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8655, \"longitude\": 2.329}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"233\", \"name\": \"Rue Saint-Honoré\", \"apt\": \"\"}, \"formatted\": \"233 Rue Saint-Honoré, 75001 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75001\", \"subdivision\": \"IDF\"}",
"phone": "01 42 61 63 13",
"website": "https://www.miller-bijouterie.com",
"hours": "Lun-Sam 10:30-18:00",
"category": "Bijoux Vintage",
"desc_fr": "Miller Bijouterie est une référence parisienne pour les bijoux et montres de luxe d'occasion, installée rue Saint-Honoré depuis plusieurs décennies. Expertise et authenticité pour une clientèle exigeante.",
"desc_en": "Miller Bijouterie is a Parisian reference for second-hand luxury jewellery and watches, established on Rue Saint-Honoré for several decades. Expertise and authenticity for a discerning clientele.",
"lat": 48.8655,
"lon": 2.329,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAweowMmgb6Sd1a1WX0cC0OlXsDro9H_pP1pYMERyn-fkQgTQs-l2dQ2bfV4q1AqBuSHNEioJeES82DiyoSCaPhvrWSUSDB3XiMSCLFYVCkEi2suN3IBNoxTfQBzsIzrc91CTzV-WS=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAweowMmgb6Sd1a1WX0cC0OlXsDro9H_pP1pYMERyn-fkQgTQs-l2dQ2bfV4q1AqBuSHNEioJeES82DiyoSCaPhvrWSUSDB3XiMSCLFYVCkEi2suN3IBNoxTfQBzsIzrc91CTzV-WS=w800-h600-k-no"
],
"status": "published"
},
{
"id": "moynat",
"name": "Moynat",
"badge": "Maroquinerie · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8655, \"longitude\": 2.327}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"348\", \"name\": \"Rue Saint-Honoré\", \"apt\": \"\"}, \"formatted\": \"348 Rue Saint-Honoré, 75001 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75001\", \"subdivision\": \"IDF\"}",
"phone": "01 47 03 83 97",
"website": "https://www.moynat.com",
"hours": "Lun-Sam 10:30-19:00",
"category": "Maroquinerie",
"desc_fr": "Fondée en 1849, Moynat est l'une des plus anciennes maisons parisiennes de malles et maroquinerie. Ressuscitée en 2011, elle perpétue un savoir-faire artisanal d'exception avec des créations intemporelles rue Saint-Honoré.",
"desc_en": "Founded in 1849, Moynat is one of the oldest Parisian houses of trunks and leather goods. Revived in 2011, it perpetuates exceptional craftsmanship with timeless creations on Rue Saint-Honoré.",
"lat": 48.8655,
"lon": 2.327,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAweob9p9mTH-Qy6WuksJZ24oksBRRvebbkT8RZYZOS9aZmhaM1oYUjO_Hh1MjeH0eMOlPxWellD60ehd7RkTwYVhgQcUEoJYixBlhOyQOMmUmbC1hubUkgLELDwQgPgMoKMQK2Oi9qe35dd6S=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAweob9p9mTH-Qy6WuksJZ24oksBRRvebbkT8RZYZOS9aZmhaM1oYUjO_Hh1MjeH0eMOlPxWellD60ehd7RkTwYVhgQcUEoJYixBlhOyQOMmUmbC1hubUkgLELDwQgPgMoKMQK2Oi9qe35dd6S=w800-h600-k-no"
],
"status": "published"
},
{
"id": "van-cleef-et-arpels-place-vendome",
"name": "Van Cleef & Arpels Place Vendôme",
"badge": "Bijouterie Fine · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8672, \"longitude\": 2.3294}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"22-24\", \"name\": \"Place Vendôme\", \"apt\": \"\"}, \"formatted\": \"22-24 Place Vendôme, 75001 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75001\", \"subdivision\": \"IDF\"}",
"phone": "01 55 04 11 11",
"website": "https://www.vancleefarpels.com",
"hours": "Lun-Sam 10:00-19:00",
"category": "Bijouterie Fine",
"desc_fr": "Depuis 1906, Van Cleef & Arpels incarne l'excellence de la joaillerie française depuis sa boutique mythique Place Vendôme. Chaque pièce raconte une histoire poétique alliant gemmes rares et savoir-faire d'exception.",
"desc_en": "Since 1906, Van Cleef & Arpels has embodied the excellence of French jewellery from its iconic boutique on Place Vendôme. Each piece tells a poetic story combining rare gemstones and exceptional craftsmanship.",
"lat": 48.8672,
"lon": 2.3294,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAwepHjAs0cu4lDBCrsDnC5NIDjcSBwDyTzcs5sOI7gnzReHoyzKwB7eyqxtnA9KpmkN0ZZUR7yBV4T2oBHcCC4PbXW96_SKmwkUQsZuuGkOtknEKiSS_M61jMrq2hXHZo5z2wLE1UiUVSog1M=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAwepHjAs0cu4lDBCrsDnC5NIDjcSBwDyTzcs5sOI7gnzReHoyzKwB7eyqxtnA9KpmkN0ZZUR7yBV4T2oBHcCC4PbXW96_SKmwkUQsZuuGkOtknEKiSS_M61jMrq2hXHZo5z2wLE1UiUVSog1M=w800-h600-k-no"
],
"status": "published"
},
{
"id": "piaget-boutique-paris-vendome",
"name": "Piaget Boutique Paris Vendôme",
"badge": "Horlogerie & Bijoux · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8672, \"longitude\": 2.3294}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"16\", \"name\": \"Place Vendôme\", \"apt\": \"\"}, \"formatted\": \"16 Place Vendôme, 75001 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75001\", \"subdivision\": \"IDF\"}",
"phone": "01 55 35 32 80",
"website": "https://www.piaget.com",
"hours": "Lun-Sam 10:00-19:00",
"category": "Horlogerie & Bijoux",
"desc_fr": "Piaget, maison horlogère et joaillière genevoise fondée en 1874, rayonne depuis sa boutique Place Vendôme. Entre montres ultra-plates et bijoux sertis de pierres fines, Piaget est synonyme d'élégance discrète.",
"desc_en": "Piaget, a Genevan watchmaking and jewellery house founded in 1874, shines from its Place Vendôme boutique. Between ultra-thin watches and jewels set with precious stones, Piaget is synonymous with discreet elegance.",
"lat": 48.8672,
"lon": 2.3294,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAwerITVrwmiMZRhIiAfsnbmUnIcGC2KdwKIR1AyAc64UaTn0BYpJ6NWBVzQlv7whMabWRFPTtUWcBsgFCpgjW3WF6S7u8m2eytgQpeOUa5h6ly_rapH8nw-33iKdZcuCRSZ_UEoMZoHx71ESw=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAwerITVrwmiMZRhIiAfsnbmUnIcGC2KdwKIR1AyAc64UaTn0BYpJ6NWBVzQlv7whMabWRFPTtUWcBsgFCpgjW3WF6S7u8m2eytgQpeOUa5h6ly_rapH8nw-33iKdZcuCRSZ_UEoMZoHx71ESw=w800-h600-k-no"
],
"status": "published"
},
{
"id": "le-palais-du-stylo",
"name": "Le Palais du Stylo",
"badge": "Papeterie Fine · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8734, \"longitude\": 2.3296}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"9\", \"name\": \"Rue Auber\", \"apt\": \"\"}, \"formatted\": \"9 Rue Auber, 75009 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75009\", \"subdivision\": \"IDF\"}",
"phone": "01 47 42 31 42",
"website": "https://www.lepalaidustylo.fr",
"hours": "Lun-Sam 9:30-18:30",
"category": "Papeterie Fine",
"desc_fr": "Le Palais du Stylo est une institution parisienne de la papeterie fine, spécialisée dans les stylos de luxe des plus grandes maisons — Montblanc, Waterman, Cross. Un temple discret dédié à l'art d'écrire.",
"desc_en": "Le Palais du Stylo is a Parisian institution of fine stationery, specialising in luxury pens from the greatest houses — Montblanc, Waterman, Cross. A discreet temple dedicated to the art of writing.",
"lat": 48.8734,
"lon": 2.3296,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAweqHXMCcM9_TqmBY8KReigjPb7O88bJ7nYoZXqiKAu-8eNtrn9NNvXdaIYHMnhyyZwyqol0JFwpYuCLfPF1oN3AJ88Q-xoAlbFWbynSy1Fojjy7u281Xisogs9FmrBRqG0KNOy4=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAweqHXMCcM9_TqmBY8KReigjPb7O88bJ7nYoZXqiKAu-8eNtrn9NNvXdaIYHMnhyyZwyqol0JFwpYuCLfPF1oN3AJ88Q-xoAlbFWbynSy1Fojjy7u281Xisogs9FmrBRqG0KNOy4=w800-h600-k-no"
],
"status": "published"
},
{
"id": "rives-paris",
"name": "RIVES PARIS",
"badge": "Tailleur Sur Mesure · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8752, \"longitude\": 2.318}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"23\", \"name\": \"Rue Pasquier\", \"apt\": \"\"}, \"formatted\": \"23 Rue Pasquier, 75008 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75008\", \"subdivision\": \"IDF\"}",
"phone": "01 40 07 05 52",
"website": "https://www.rivesparis.com",
"hours": "Lun-Sam 10:00-19:30",
"category": "Tailleur Sur Mesure",
"desc_fr": "Rives Paris est un atelier de tailleur de luxe pour hommes installé rue Pasquier. Fondé par des passionnés de couture masculine, il propose des costumes sur-mesure d'exception alliant tissus anglais et italiens de premier ordre.",
"desc_en": "Rives Paris is a luxury tailor's workshop for men on Rue Pasquier. Founded by passionate men's tailoring enthusiasts, it offers exceptional bespoke suits combining first-rate English and Italian fabrics.",
"lat": 48.8752,
"lon": 2.318,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAweqeKotxp69wopCNO8pgpKwl_93m6TE3782_wyICLMS5-Ckh7vKSUONrjikecdArTHJTDid_aoSzNxX_kjJSZ9WxaJR8Q3IT2uheiErMiQHE9EX_uYjCpDDPWPIlH-WBQbnxATPw=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAweqeKotxp69wopCNO8pgpKwl_93m6TE3782_wyICLMS5-Ckh7vKSUONrjikecdArTHJTDid_aoSzNxX_kjJSZ9WxaJR8Q3IT2uheiErMiQHE9EX_uYjCpDDPWPIlH-WBQbnxATPw=w800-h600-k-no"
],
"status": "published"
},
{
"id": "bourrienne-paris-x",
"name": "Bourrienne Paris X",
"badge": "Mode · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8753, \"longitude\": 2.351}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"58\", \"name\": \"Rue d'Hauteville\", \"apt\": \"\"}, \"formatted\": \"58 Rue d'Hauteville, 75010 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75010\", \"subdivision\": \"IDF\"}",
"phone": "07 64 30 63 04",
"website": "https://www.bourrienneparisx.com",
"hours": "Lun-Sam 11:00-19:00",
"category": "Mode",
"desc_fr": "Bourrienne Paris X est une maison de chemiserie masculine fondée dans le 10e arrondissement de Paris. Chemises intemporelles fabriquées en France dans des matières nobles, pour un vestiaire masculin élégant et durable.",
"desc_en": "Bourrienne Paris X is a men's shirt-making house founded in the 10th arrondissement of Paris. Timeless shirts made in France from noble materials, for an elegant and durable men's wardrobe.",
"lat": 48.8753,
"lon": 2.351,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAwepMfz9Sv5sHLtxX-R_R_QTkgankE9PEihV6iKBs42IMEELUOzFAZXYEslka_RYfAeCO38aoYwGRXC-fEV-ZPg9YlkG7mhxiKRaZOidkMwI9ZxKVHMXwXSyfmxyu85oycHCWmt-r=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAwepMfz9Sv5sHLtxX-R_R_QTkgankE9PEihV6iKBs42IMEELUOzFAZXYEslka_RYfAeCO38aoYwGRXC-fEV-ZPg9YlkG7mhxiKRaZOidkMwI9ZxKVHMXwXSyfmxyu85oycHCWmt-r=w800-h600-k-no"
],
"status": "published"
},
{
"id": "frederic-costa",
"name": "Frederic Costa",
"badge": "Mode Homme · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.879, \"longitude\": 2.3226}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"45\", \"name\": \"Rue d'Amsterdam\", \"apt\": \"\"}, \"formatted\": \"45 Rue d'Amsterdam, 75008 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75008\", \"subdivision\": \"IDF\"}",
"phone": "01 48 78 25 71",
"website": "https://www.fredericcosta.fr",
"hours": "Lun-Sam 10:00-19:30",
"category": "Mode Homme",
"desc_fr": "Frédéric Costa (anciennement Howard's) est une référence incontournable de la mode masculine chic à Paris. Cette boutique de la rue d'Amsterdam propose des costumes sur-mesure et du prêt-à-porter élégant pour hommes exigeants.",
"desc_en": "Frederic Costa (formerly Howard's) is an essential reference for chic men's fashion in Paris. This boutique on Rue d'Amsterdam offers bespoke suits and elegant ready-to-wear for discerning men.",
"lat": 48.879,
"lon": 2.3226,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAweoJod5mni_HtzFlsE6-ssFDV8qGxXMAL4jFNEE_pEZcyss2pA5OT2Vb_EEM54l9-c-6zkzQYuFoWIyWvy9sXyuuw3_1lI5uxPI_vuaMd7k41njrsS_32U7e4eej4gcKheqVNigJ=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAweoJod5mni_HtzFlsE6-ssFDV8qGxXMAL4jFNEE_pEZcyss2pA5OT2Vb_EEM54l9-c-6zkzQYuFoWIyWvy9sXyuuw3_1lI5uxPI_vuaMd7k41njrsS_32U7e4eej4gcKheqVNigJ=w800-h600-k-no"
],
"status": "published"
},
{
"id": "letrange-paris",
"name": "LÉTRANGE Paris",
"badge": "Maroquinerie · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8696, \"longitude\": 2.332}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"4\", \"name\": \"Rue de la Paix\", \"apt\": \"\"}, \"formatted\": \"4 Rue de la Paix, 75002 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75002\", \"subdivision\": \"IDF\"}",
"phone": "06 62 99 22 95",
"website": "",
"hours": "Lun-Sam 10:00-18:30",
"category": "Maroquinerie",
"desc_fr": "",
"desc_en": "",
"lat": 48.8696,
"lon": 2.332,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAwergV8h33mD9MhrpXx9foaArrJUWOQ4JvrAGlwsP6KPircncI0xBLrCDMFHluM65iwAwEtYqOdYDXqG7dJpNmYOTYece5-rKowPnc2QZe1rN_SOKPWSOy95KIm80eGVuSRi4YwFohGh4Hzg=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAwergV8h33mD9MhrpXx9foaArrJUWOQ4JvrAGlwsP6KPircncI0xBLrCDMFHluM65iwAwEtYqOdYDXqG7dJpNmYOTYece5-rKowPnc2QZe1rN_SOKPWSOy95KIm80eGVuSRi4YwFohGh4Hzg=w800-h600-k-no"
],
"status": "published"
},
{
"id": "lassaussois-montres-et-bijoux",
"name": "Lassaussois - Montres et Bijoux",
"badge": "Horlogerie & Bijoux · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8496, \"longitude\": 2.331}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"58\", \"name\": \"Rue de Rennes\", \"apt\": \"\"}, \"formatted\": \"58 Rue de Rennes, 75006 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75006\", \"subdivision\": \"IDF\"}",
"phone": "01 46 34 71 38",
"website": "",
"hours": "Lun-Sam 10:00-19:00",
"category": "Horlogerie & Bijoux",
"desc_fr": "",
"desc_en": "",
"lat": 48.8496,
"lon": 2.331,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAwepfpQvQW3BgUTCEik9SDYya5MDaDe1CWLf-PtiEHUn8uLyl-Zm7aJapeAvkd6fHv-ll7OdKLBoiE59_SxPvU0rvp4zyMhBT-NGPFO0i86263HVHOxVbvrC43w2ihb0-xr4viOh-EOP-hOM=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAwepfpQvQW3BgUTCEik9SDYya5MDaDe1CWLf-PtiEHUn8uLyl-Zm7aJapeAvkd6fHv-ll7OdKLBoiE59_SxPvU0rvp4zyMhBT-NGPFO0i86263HVHOxVbvrC43w2ihb0-xr4viOh-EOP-hOM=w800-h600-k-no"
],
"status": "published"
},
{
"id": "mamie-blue",
"name": "Mamie Blue",
"badge": "Mode Vintage · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8774, \"longitude\": 2.345}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"69\", \"name\": \"Rue Marguerite de Rochechouart\", \"apt\": \"\"}, \"formatted\": \"69 Rue Marguerite de Rochechouart, 75009 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75009\", \"subdivision\": \"IDF\"}",
"phone": "01 42 81 10 42",
"website": "",
"hours": "Lun-Sam 11:00-19:30",
"category": "Mode Vintage",
"desc_fr": "",
"desc_en": "",
"lat": 48.8774,
"lon": 2.345,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAweovYpn8IBbTav84ydWcp8CxHNZmo-ftuPopndpNiX0ECGCeE20BmidFJCbAT9yHhT-O7HH1DkF5ofQoK2bMHdILs2jkJs-mAxQOpCilmC64OVKwtYUDfVkYJxsjn43ttsl5x4m4=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAweovYpn8IBbTav84ydWcp8CxHNZmo-ftuPopndpNiX0ECGCeE20BmidFJCbAT9yHhT-O7HH1DkF5ofQoK2bMHdILs2jkJs-mAxQOpCilmC64OVKwtYUDfVkYJxsjn43ttsl5x4m4=w800-h600-k-no"
],
"status": "published"
},
{
"id": "plus-que-parfait",
"name": "Plus que parfait",
"badge": "Mode Homme · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8573, \"longitude\": 2.353}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"23\", \"name\": \"Rue des Blancs Manteaux\", \"apt\": \"\"}, \"formatted\": \"23 Rue des Blancs Manteaux, 75004 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75004\", \"subdivision\": \"IDF\"}",
"phone": "01 42 71 09 05",
"website": "",
"hours": "Lun-Sam 11:00-20:00",
"category": "Mode Homme",
"desc_fr": "",
"desc_en": "",
"lat": 48.8573,
"lon": 2.353,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAwepbWEyZkh5RtHgYO-TmjLBLCvoFeiZQPwypMCH9QKMqQzt09kaSvVYQEDAxNntyE4TylGT7MjJtWATVO6GqAwQiRCPAzq_8FmAJxcuFhxBc1dKLoPNE4YrbFMyfG_uy0bkMy98gVg=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAwepbWEyZkh5RtHgYO-TmjLBLCvoFeiZQPwypMCH9QKMqQzt09kaSvVYQEDAxNntyE4TylGT7MjJtWATVO6GqAwQiRCPAzq_8FmAJxcuFhxBc1dKLoPNE4YrbFMyfG_uy0bkMy98gVg=w800-h600-k-no"
],
"status": "published"
},
{
"id": "mes-demoiselles",
"name": "Mes Demoiselles",
"badge": "Mode · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8625, \"longitude\": 2.3589}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"45\", \"name\": \"Rue Charlot\", \"apt\": \"\"}, \"formatted\": \"45 Rue Charlot, 75003 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75003\", \"subdivision\": \"IDF\"}",
"phone": "01 49 96 50 75",
"website": "https://www.mesdemoisellesparis.com",
"hours": "Lun-Sam 10:30-19:30",
"category": "Mode",
"desc_fr": "Mes Demoiselles est une marque de prêt-à-porter parisienne à l'esprit libre et bohème, fondée dans le Marais. Ses créations associent matières nobles, imprimés poétiques et coupes féminines pour un style parisien inimitable.",
"desc_en": "Mes Demoiselles is a free-spirited and bohemian Parisian ready-to-wear brand, founded in the Marais. Its creations combine noble materials, poetic prints and feminine cuts for an inimitable Parisian style.",
"lat": 48.8625,
"lon": 2.3589,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAweqY4GMbtignrY-LvVR-m0-ZjPv-Q4_fmT10UUqb5BXmG0pW1wRUw7BVT42JxchiCKVwansQwEuD3wOIA_t2DKQP-aGDxxEaw76-kxCOgIMCSSB7PW-Q5fkATTolt1z6ou6VHkHF=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAweqY4GMbtignrY-LvVR-m0-ZjPv-Q4_fmT10UUqb5BXmG0pW1wRUw7BVT42JxchiCKVwansQwEuD3wOIA_t2DKQP-aGDxxEaw76-kxCOgIMCSSB7PW-Q5fkATTolt1z6ou6VHkHF=w800-h600-k-no"
],
"status": "published"
},
{
"id": "systeme-solere",
"name": "Système Solère",
"badge": "Mode Vintage · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8541, \"longitude\": 2.3566}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"23\", \"name\": \"Rue des Écouffes\", \"apt\": \"\"}, \"formatted\": \"23 Rue des Écouffes, 75004 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75004\", \"subdivision\": \"IDF\"}",
"phone": "",
"website": "",
"hours": "Ferme à 19:30",
"category": "Mode Vintage",
"desc_fr": "",
"desc_en": "",
"lat": 48.8541,
"lon": 2.3566,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAweoRAgsfFpM21kAsOOK87qNLuHn1ElAqEJ9nD1fVdKWYcqXEmCG753hRtnzoE0OgDtSRs9vQ5DVzbKsp6W-Ctrw5mkbI8YpVqUmnP2g_aP1TTbeWisLe25B_xexJ1drh0Z2n5m0W=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAweoRAgsfFpM21kAsOOK87qNLuHn1ElAqEJ9nD1fVdKWYcqXEmCG753hRtnzoE0OgDtSRs9vQ5DVzbKsp6W-Ctrw5mkbI8YpVqUmnP2g_aP1TTbeWisLe25B_xexJ1drh0Z2n5m0W=w800-h600-k-no"
],
"status": "published"
},
{
"id": "galerie-vivienne",
"name": "Galerie Vivienne",
"badge": "Galerie Marchande · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8666, \"longitude\": 2.3375}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"4\", \"name\": \"Rue des Petits Champs\", \"apt\": \"\"}, \"formatted\": \"4 Rue des Petits Champs, 75002 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75002\", \"subdivision\": \"IDF\"}",
"phone": "",
"website": "https://www.galerie-vivienne.com",
"hours": "Lun-Dim 8:30-20:00",
"category": "Galerie Marchande",
"desc_fr": "La Galerie Vivienne, construite en 1823, est l'une des plus belles galeries couvertes de Paris. Classée monument historique, elle abrite boutiques de luxe, librairies rares et restaurants dans un décor de mosaïques et verrières spectaculaires.",
"desc_en": "The Galerie Vivienne, built in 1823, is one of the most beautiful covered galleries in Paris. Listed as a historic monument, it houses luxury boutiques, rare bookshops and restaurants in a setting of spectacular mosaics and glass roofs.",
"lat": 48.8666,
"lon": 2.3375,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAwepG1Kjl_QbxdyD3f7cAUmj16kXMVJnMxugprOsJ6C6pwZ2xehrxo7jdKPyRzeaY7990YQz-u-tSnXI0SGDuaDaGHwRQ_Aq8e6e2qKLoYi1C02Q9KPlimOl9fT2PxBR3evb9jRRbtg=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAwepG1Kjl_QbxdyD3f7cAUmj16kXMVJnMxugprOsJ6C6pwZ2xehrxo7jdKPyRzeaY7990YQz-u-tSnXI0SGDuaDaGHwRQ_Aq8e6e2qKLoYi1C02Q9KPlimOl9fT2PxBR3evb9jRRbtg=w800-h600-k-no"
],
"status": "published"
},
{
"id": "depot-vente-luxe-louise-paris",
"name": "Dépôt Vente Luxe LOUISE Paris",
"badge": "Dépôt-vente Luxe · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.868, \"longitude\": 2.357}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"10\", \"name\": \"Rue de Lancry\", \"apt\": \"\"}, \"formatted\": \"10 Rue de Lancry, 75010 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75010\", \"subdivision\": \"IDF\"}",
"phone": "06 64 86 08 03",
"website": "",
"hours": "Mar-Sam 11:00-19:30",
"category": "Dépôt-vente Luxe",
"desc_fr": "",
"desc_en": "",
"lat": 48.868,
"lon": 2.357,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAwep6yAenQIB9aiBfRejLrg1wL8FJZJLwb0VYfTobwTDgFtYFD5pgxwHHGsmOZSZ0rc4yyOY6KG9Wkyb1iC8XbT_na0yl2AMygGoJbfJV3d1-Koyr9TMUWbSgQTjqnleTnjWhj-wirZwpdMZ9=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAwep6yAenQIB9aiBfRejLrg1wL8FJZJLwb0VYfTobwTDgFtYFD5pgxwHHGsmOZSZ0rc4yyOY6KG9Wkyb1iC8XbT_na0yl2AMygGoJbfJV3d1-Koyr9TMUWbSgQTjqnleTnjWhj-wirZwpdMZ9=w800-h600-k-no"
],
"status": "published"
},
{
"id": "ale-paris-luxury-vintage-boutique-and-custom-",
"name": "ALE Paris - Luxury Vintage Boutique and Custom Tailoring",
"badge": "Mode Vintage · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8648545, \"longitude\": 2.3493757}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"6\", \"name\": \"Pass. du Grand Cerf\", \"apt\": \"\"}, \"formatted\": \"6 Pass. du Grand Cerf, 75002 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75002\", \"subdivision\": \"IDF\"}",
"phone": "",
"website": "https://www.aleparis.fr",
"hours": "Sat 1–7 PM | Mon 11 AM–7 PM | Tue 11 AM–7 PM",
"category": "Mode Vintage",
"desc_fr": "ALE Paris est un dépôt-vente de luxe vintage et une maison de création sur mesure installée dans le Passage du Grand Cerf depuis 2018. Alejandro propose une sélection rigoureuse de pièces Chanel, YSL, Mugler et Dior des années 80 à 2000.",
"desc_en": "ALE Paris is a luxury vintage consignment boutique and bespoke creation house in the Passage du Grand Cerf since 2018, offering a rigorous selection of Chanel, YSL, Mugler and Dior pieces from the 80s to 2000s.",
"lat": 48.8648545,
"lon": 2.3493757,
"main_photo": "",
"photos": [],
"status": "published"
},
{
"id": "iconique-luxe-paris",
"name": "Iconique Luxe Paris",
"badge": "Dépôt-vente Luxe · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.854226, \"longitude\": 2.3302407}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"50\", \"name\": \"Rue des Saints-Pères\", \"apt\": \"\"}, \"formatted\": \"50 Rue des Saints-Pères, 75007 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75007\", \"subdivision\": \"IDF\"}",
"phone": "+33 1 77 32 05 78",
"website": "https://iconiqueluxe.com",
"hours": "Lun-Sam 10:30 AM–7:30 PM",
"category": "Dépôt-vente Luxe",
"desc_fr": "Iconique Luxe Paris est un dépôt-vente de luxe confidentiel rue des Saints-Pères, spécialisé dans les pièces Chanel, Hermès et Dior. Une sélection irréprochable dans un cadre élégant du 7e arrondissement.",
"desc_en": "Iconique Luxe Paris is a discreet luxury consignment boutique on Rue des Saints-Pères, specialising in Chanel, Hermès and Dior pieces in an elegant 7th arrondissement setting.",
"lat": 48.854226,
"lon": 2.3302407,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAweqYiMdj_YJdRs6j_tVZI_fXs7UR-aRFQyKdLUhqMXzlZG-FLcHIQN925V1ROvl9-3Kh3tQusaXvFUl_CmyzdEpXhjj5NqbntAnfnWQUkl59SNpzmV207rdolYGnwpbljOvoVhHG=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAweqYiMdj_YJdRs6j_tVZI_fXs7UR-aRFQyKdLUhqMXzlZG-FLcHIQN925V1ROvl9-3Kh3tQusaXvFUl_CmyzdEpXhjj5NqbntAnfnWQUkl59SNpzmV207rdolYGnwpbljOvoVhHG=w800-h600-k-no"
],
"status": "published"
},
{
"id": "sissi-s-corner-depot-vente-luxe-sissi-s-corne",
"name": "Sissi's corner - Dépôt-vente luxe/ Sissi's corner Luxury Second Hand Shop",
"badge": "Mode Vintage · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8547283, \"longitude\": 2.3675749}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"20\", \"name\": \"Rue des Tournelles\", \"apt\": \"\"}, \"formatted\": \"20 Rue des Tournelles, 75004 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75004\", \"subdivision\": \"IDF\"}",
"phone": "+33 6 62 86 14 85",
"website": "",
"hours": "Sat 2–7:30 PM | Wed 12–7 PM | Thu 12–7 PM",
"category": "Mode Vintage",
"desc_fr": "Sissi's Corner est un dépôt-vente de luxe emblématique du Marais rue des Tournelles, proposant sacs, bijoux et vêtements de grandes maisons dans un esprit accessible et chaleureux.",
"desc_en": "Sissi's Corner is an iconic luxury consignment boutique in the Marais on Rue des Tournelles, offering bags, jewellery and clothing from major houses in an accessible and warm spirit.",
"lat": 48.8547283,
"lon": 2.3675749,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAweqrb6-FDJALgm9ZchAms3U3cgshPUG2kdJ9Msy9ewaEUHInIOSFDxP8ZAebdzO4e6kDSUMDjADeyN2vnEB6DkTGYQtFsVfqP_WG2qxSJ9WLxQMO8xJVzGNPTqLxNHDZcXe0_12t3J8mAL-9=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAweqrb6-FDJALgm9ZchAms3U3cgshPUG2kdJ9Msy9ewaEUHInIOSFDxP8ZAebdzO4e6kDSUMDjADeyN2vnEB6DkTGYQtFsVfqP_WG2qxSJ9WLxQMO8xJVzGNPTqLxNHDZcXe0_12t3J8mAL-9=w800-h600-k-no"
],
"status": "published"
},
{
"id": "cornerluxe",
"name": "CornerLuxe",
"badge": "Dépôt-vente Luxe · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8578039, \"longitude\": 2.3043425}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"45\", \"name\": \"Av. Bosquet\", \"apt\": \"\"}, \"formatted\": \"45 Av. Bosquet, 75007 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75007\", \"subdivision\": \"IDF\"}",
"phone": "+33 1 44 18 31 50",
"website": "https://www.cornerluxe.com",
"hours": "Lun-Sam 10:30 AM–1:30 PM, 2:30–6:30 PM",
"category": "Dépôt-vente Luxe",
"desc_fr": "CornerLuxe avenue Bosquet est l'une des 3 boutiques de ce réseau expert en dépôt-vente de luxe depuis 20 ans. Sacs, montres et bijoux Louis Vuitton, Hermès, Chanel certifiés authentiques.",
"desc_en": "CornerLuxe on Avenue Bosquet is one of 3 boutiques of this expert luxury consignment network with 20 years of experience, offering certified authentic Louis Vuitton, Hermès and Chanel pieces.",
"lat": 48.8578039,
"lon": 2.3043425,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAweqdmimAPpP6V-DFyC9nRXA47i1u6yPqJX6g4seKBNkVrfBZN0sFZEsOKP-pqvzgFX0NAbaSStVpA3WhyhOZuZe6jmkWX67Axl1zBq4We8PBwSWERN58khop2BBmmrQ5YK2kQsd3yJsjY8Cm=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAweqdmimAPpP6V-DFyC9nRXA47i1u6yPqJX6g4seKBNkVrfBZN0sFZEsOKP-pqvzgFX0NAbaSStVpA3WhyhOZuZe6jmkWX67Axl1zBq4We8PBwSWERN58khop2BBmmrQ5YK2kQsd3yJsjY8Cm=w800-h600-k-no"
],
"status": "published"
},
{
"id": "fashion-vintage-carole-bigielman",
"name": "fashion vintage / Carole Bigielman",
"badge": "Mode Vintage · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8609612, \"longitude\": 2.3794414}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"12\", \"name\": \"Rue Rochebrune\", \"apt\": \"\"}, \"formatted\": \"12 Rue Rochebrune, 75011 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75011\", \"subdivision\": \"IDF\"}",
"phone": "+33 6 63 79 72 04",
"website": "https://www.la-mode-vintage.com",
"hours": "Lun-Sam 11 AM–7 PM",
"category": "Mode Vintage",
"desc_fr": "La boutique de Carole Bigielman est un showroom vintage de luxe dans le 11e proposant une sélection remarquable de pièces signées Hermès, Chanel et YSL. Une adresse de connaisseur notée 4,9/5.",
"desc_en": "Carole Bigielman's boutique is a luxury vintage showroom in the 11th offering a remarkable selection of signed Hermès, Chanel and YSL pieces, rated 4.9/5.",
"lat": 48.8609612,
"lon": 2.3794414,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAweovg9hH_jo_kto4sYt8ykSOr1w82dHmxPxsbk2jQN_c2FV4ATEFfo-t_oRQzLP2ixMWD6mLgtnAB8N_t4kBQ5Q8OaIvynrDPG1P-WYBen-Lm2FAvISRRQsle0hmeTrHqadu11HR=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAweovg9hH_jo_kto4sYt8ykSOr1w82dHmxPxsbk2jQN_c2FV4ATEFfo-t_oRQzLP2ixMWD6mLgtnAB8N_t4kBQ5Q8OaIvynrDPG1P-WYBen-Lm2FAvISRRQsle0hmeTrHqadu11HR=w800-h600-k-no"
],
"status": "published"
},
{
"id": "the-shop-kroll-com",
"name": "The shop Kroll.com",
"badge": "Dépôt-vente Luxe · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8846762, \"longitude\": 2.3119895}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"86\", \"name\": \"R. de Lévis\", \"apt\": \"\"}, \"formatted\": \"86 R. de Lévis, 75017 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75017\", \"subdivision\": \"IDF\"}",
"phone": "+33 9 50 34 95 47",
"website": "https://www.laboutiquedekroll.com",
"hours": "Lun-Sam 2–7 PM",
"category": "Dépôt-vente Luxe",
"desc_fr": "La Boutique de Kroll est un dépôt-vente select rue de Lévis dans le 17e. Vêtements et accessoires de créateurs soigneusement expertisés dans une ambiance boutique chic et personnalisée.",
"desc_en": "La Boutique de Kroll is a select consignment boutique on Rue de Lévis in the 17th, offering carefully authenticated designer clothing and accessories in a chic atmosphere.",
"lat": 48.8846762,
"lon": 2.3119895,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAweodoEy_Xfkr_wKRoMQS3X_LCc7G0VLpSEOHxhKvlPy7H8zYJWEgJZuylEtzlJnHu0z3tMtD_6BERaz_o_684Dxt0isSYnWYWnx96V27YOEA7M3F1SXNzhyhQk2mlMKZJyyFWJI=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAweodoEy_Xfkr_wKRoMQS3X_LCc7G0VLpSEOHxhKvlPy7H8zYJWEgJZuylEtzlJnHu0z3tMtD_6BERaz_o_684Dxt0isSYnWYWnx96V27YOEA7M3F1SXNzhyhQk2mlMKZJyyFWJI=w800-h600-k-no"
],
"status": "published"
},
{
"id": "mention-luxe",
"name": "Mention Luxe",
"badge": "Mode Vintage · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8571362, \"longitude\": 2.2725657}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"16\", \"name\": \"Av. Mozart\", \"apt\": \"\"}, \"formatted\": \"16 Av. Mozart, 75016 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75016\", \"subdivision\": \"IDF\"}",
"phone": "+33 6 33 40 45 98",
"website": "https://www.instagram.com/mentionluxeparis/?hl=fr",
"hours": "Mon 11 AM–6:30 PM | Tue 11 AM–6:30 PM | Wed 11 AM–6:30 PM",
"category": "Mode Vintage",
"desc_fr": "Mention Luxe est un dépôt-vente de luxe réputé avec plusieurs adresses parisiennes, spécialisé dans les sacs et accessoires de grandes maisons pour une clientèle avertie.",
"desc_en": "Mention Luxe is a well-regarded luxury consignment boutique with several Parisian addresses, specialising in bags and accessories from major houses for a discerning clientele.",
"lat": 48.8571362,
"lon": 2.2725657,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAweq3JuiaNigZrjWT4_8eomPIFUkFUwKSor49wzccgpnvQafhLpKiVrXaTpjeXEnPOUK50JKyf0vFzfjKZo9nvUxyxi7tzSsB2NUSXIsLSIxtYvYe_Ie-Ul1qZSrcLGHRIavPRMc=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAweq3JuiaNigZrjWT4_8eomPIFUkFUwKSor49wzccgpnvQafhLpKiVrXaTpjeXEnPOUK50JKyf0vFzfjKZo9nvUxyxi7tzSsB2NUSXIsLSIxtYvYe_Ie-Ul1qZSrcLGHRIavPRMc=w800-h600-k-no"
],
"status": "published"
},
{
"id": "opulence-luxury-et-vintage-jean-du-bellay",
"name": "Opulence Luxury & Vintage Jean du Bellay",
"badge": "Mode Vintage · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8532083, \"longitude\": 2.3535629}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"3\", \"name\": \"Rue Jean du Bellay\", \"apt\": \"\"}, \"formatted\": \"3 Rue Jean du Bellay, 75004 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75004\", \"subdivision\": \"IDF\"}",
"phone": "+33 6 48 91 79 86",
"website": "https://www.opulencevintage.com",
"hours": "",
"category": "Mode Vintage",
"desc_fr": "Opulence Vintage propose sur l'île Saint-Louis une sélection de sacs et bijoux vintage de luxe dans l'un des quartiers les plus romantiques de Paris, à deux pas de Notre-Dame.",
"desc_en": "Opulence Vintage offers on Île Saint-Louis a selection of luxury vintage bags and jewellery in one of Paris's most romantic neighbourhoods, steps from Notre-Dame.",
"lat": 48.8532083,
"lon": 2.3535629,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAweqBrZl4c9zOYmG4Q0xDGaWxBoGQ0fGLHffi1oMpAbXu2KoQWKNM3ykrwxbWNUhtGkWK69r-nSvWxuv1kSMMewGO8Z3n_YCFNCg-0e0cLwxkQfCV8E7e2rgPFPyRO4ZcBF5kGTTwpvuI2JzU=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAweqBrZl4c9zOYmG4Q0xDGaWxBoGQ0fGLHffi1oMpAbXu2KoQWKNM3ykrwxbWNUhtGkWK69r-nSvWxuv1kSMMewGO8Z3n_YCFNCg-0e0cLwxkQfCV8E7e2rgPFPyRO4ZcBF5kGTTwpvuI2JzU=w800-h600-k-no"
],
"status": "published"
},
{
"id": "allu",
"name": "Allu",
"badge": "Maroquinerie · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8683844, \"longitude\": 2.322745}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"3\", \"name\": \"Rue du Faubourg Saint-Honoré 2ème étage\", \"apt\": \"\"}, \"formatted\": \"3 Rue du Faubourg Saint-Honoré 2ème étage, 75008 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75008\", \"subdivision\": \"IDF\"}",
"phone": "+33 6 19 25 96 35",
"website": "https://sell-fr.allu-official.com",
"hours": "Lun-Sam 11 AM–7 PM",
"category": "Maroquinerie",
"desc_fr": "Allu est la première plateforme mondiale de seconde main luxe certifiée, avec une boutique au cœur du Faubourg Saint-Honoré. Sacs Chanel, montres Rolex et bijoux Cartier — achat, vente et expertise.",
"desc_en": "Allu is the world's first certified luxury second-hand platform, with a boutique in the heart of Faubourg Saint-Honoré. Chanel bags, Rolex watches and Cartier jewellery — buy, sell and authenticate.",
"lat": 48.8683844,
"lon": 2.322745,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAwerGN7ETecGUZJswarTbCTvfDvIEyMlDF78ad0ploMKrUJZTmoSijpoGBkoyxZFupjAuuXjWG7JiKu3QWcSX2uzit-MEBg1ikLfpdmOQKmyuIy2MgrKzJuS1AFJvppJQyw864WfYpw=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAwerGN7ETecGUZJswarTbCTvfDvIEyMlDF78ad0ploMKrUJZTmoSijpoGBkoyxZFupjAuuXjWG7JiKu3QWcSX2uzit-MEBg1ikLfpdmOQKmyuIy2MgrKzJuS1AFJvppJQyw864WfYpw=w800-h600-k-no"
],
"status": "published"
},
{
"id": "ibkeit-vetements-de-luxe",
"name": "IBKEIT Vêtements de luxe",
"badge": "Mode Homme · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8721392, \"longitude\": 2.3578774}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"12\", \"name\": \"Rue Hittorf\", \"apt\": \"\"}, \"formatted\": \"12 Rue Hittorf, 75010 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75010\", \"subdivision\": \"IDF\"}",
"phone": "+33 1 72 38 08 07",
"website": "",
"hours": "Lun-Sam 11 AM–8 PM",
"category": "Mode Homme",
"desc_fr": "IBKEIT est une boutique de vêtements de luxe pour hommes rue Hittorf dans le 10e. Une adresse confidentielle notée 5/5 proposant des pièces haut de gamme dans un cadre intimiste.",
"desc_en": "IBKEIT is a luxury menswear boutique on Rue Hittorf in the 10th. A discreet address rated 5/5 offering high-end pieces in an intimate setting.",
"lat": 48.8721392,
"lon": 2.3578774,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAweohcVKr6-Oy6eXOkA28dWbyoCb1IU67WAj0fWON4D0w3LaK2OvUssosVG-6EFpTe-2N7lwN-es0ZPHVJMpE0L4zOM2DUCGEkGbf1L30N9CXfmz6x-29YiIWkdYyusF6qA52uFr4CR4xUQtP=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAweohcVKr6-Oy6eXOkA28dWbyoCb1IU67WAj0fWON4D0w3LaK2OvUssosVG-6EFpTe-2N7lwN-es0ZPHVJMpE0L4zOM2DUCGEkGbf1L30N9CXfmz6x-29YiIWkdYyusF6qA52uFr4CR4xUQtP=w800-h600-k-no"
],
"status": "published"
},
{
"id": "luxspace",
"name": "LuxSpace",
"badge": "Maroquinerie · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.871057, \"longitude\": 2.3167059}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"90\", \"name\": \"Rue du Faubourg Saint-Honoré\", \"apt\": \"\"}, \"formatted\": \"90 Rue du Faubourg Saint-Honoré, 75008 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75008\", \"subdivision\": \"IDF\"}",
"phone": "+33 1 40 36 80 79",
"website": "https://www.luxspace.fr",
"hours": "Lun-Sam 10 AM–7 PM",
"category": "Maroquinerie",
"desc_fr": "LuxSpace est une boutique de luxe rue du Faubourg Saint-Honoré proposant sacs, bijoux et maroquinerie de grandes maisons. Un espace sélectif au cœur du quartier le plus exclusif de Paris.",
"desc_en": "LuxSpace is a luxury boutique on Rue du Faubourg Saint-Honoré offering bags, jewellery and leather goods from major houses in the heart of Paris's most exclusive neighbourhood.",
"lat": 48.871057,
"lon": 2.3167059,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAweo2CWQMNDBD7QodtO2QqdGzn2TbHVXaYTSBwVXm9aSjkr6xdOvbd1Y5wmHNn-PXWU77Qxe-2saWxUpwpVvchdem9mMSQqxVzC2ChrLkYwia2z0XGg3NdzT9Z09FhMxN85NL6lnrrw=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAweo2CWQMNDBD7QodtO2QqdGzn2TbHVXaYTSBwVXm9aSjkr6xdOvbd1Y5wmHNn-PXWU77Qxe-2saWxUpwpVvchdem9mMSQqxVzC2ChrLkYwia2z0XGg3NdzT9Z09FhMxN85NL6lnrrw=w800-h600-k-no"
],
"status": "published"
},
{
"id": "thanx-god-i-m-a-v-i-p",
"name": "Thanx God I'm a V.I.P.",
"badge": "Mode Vintage · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8692843, \"longitude\": 2.3604019}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"12\", \"name\": \"Rue de Lancry\", \"apt\": \"\"}, \"formatted\": \"12 Rue de Lancry, 75010 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75010\", \"subdivision\": \"IDF\"}",
"phone": "+33 1 42 03 02 09",
"website": "https://www.thanxgod.com",
"hours": "Lun-Sam 2–8 PM",
"category": "Mode Vintage",
"desc_fr": "Thanx God I'm a V.I.P. est une boutique vintage culte du 10e fondée en 1989. Pièces des années 60 aux années 90 et accessoires iconiques dans une atmosphère rock et décalée.",
"desc_en": "Thanx God I'm a V.I.P. is a cult vintage boutique in the 10th founded in 1989, offering pieces from the 60s to the 90s and iconic accessories in a rock and offbeat atmosphere.",
"lat": 48.8692843,
"lon": 2.3604019,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAwer3nE-QK9njNiDfBskfCI_goyWW3qg8fc-qxfv0mJomcpWqTVnhYy4gYnGkkxoQtMF8M1gFau7EA-uScPFNMaHYGQD_x-rTMXybpozOfeSwOUrJtGTrV1mRYtLgfZtkHWvNz6BF3_zApsWJ=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAwer3nE-QK9njNiDfBskfCI_goyWW3qg8fc-qxfv0mJomcpWqTVnhYy4gYnGkkxoQtMF8M1gFau7EA-uScPFNMaHYGQD_x-rTMXybpozOfeSwOUrJtGTrV1mRYtLgfZtkHWvNz6BF3_zApsWJ=w800-h600-k-no"
],
"status": "published"
},
{
"id": "palace-callas",
"name": "Palace Callas",
"badge": "Mode Vintage · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8552862, \"longitude\": 2.3559874}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"16\", \"name\": \"Rue du Pont Louis-Philippe\", \"apt\": \"\"}, \"formatted\": \"16 Rue du Pont Louis-Philippe, 75004 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75004\", \"subdivision\": \"IDF\"}",
"phone": "+33 6 60 20 14 50",
"website": "https://palacecallas.com",
"hours": "Lun-Sam 12:30–6:30 PM",
"category": "Mode Vintage",
"desc_fr": "Palace Callas est une boutique vintage confidentielle du Marais fondée avec un esprit éditorial pointu. Comme des Garçons, Jean Paul Gaultier, Chanel — une curation audacieuse et avant-gardiste.",
"desc_en": "Palace Callas is a discreet vintage boutique in the Marais with a sharp editorial spirit. Comme des Garçons, Jean Paul Gaultier, Chanel — a bold and avant-garde curation.",
"lat": 48.8552862,
"lon": 2.3559874,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAwerRsCGhRt9k-MZ1pAkQqmZGyVghl-wRx82G54Nbb4gNGEjK_RS8wSiqYlWffjyc_mG9jE4pV5NAV89QS0ItlOEoBzjvRKJ0d-V5-TKlFj5aGZ7agnD1m9S3PNdm687U1t3_inY=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAwerRsCGhRt9k-MZ1pAkQqmZGyVghl-wRx82G54Nbb4gNGEjK_RS8wSiqYlWffjyc_mG9jE4pV5NAV89QS0ItlOEoBzjvRKJ0d-V5-TKlFj5aGZ7agnD1m9S3PNdm687U1t3_inY=w800-h600-k-no"
],
"status": "published"
},
{
"id": "citizen-concept-store-depot-vente-vintage-et-",
"name": "Citizen Concept Store Dépôt-Vente vintage & luxury Paris",
"badge": "Dépôt-vente Luxe · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8602293, \"longitude\": 2.3638994}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"22\", \"name\": \"RUE DE THORIGNY\", \"apt\": \"\"}, \"formatted\": \"22 RUE DE THORIGNY, 8 Rue du Roi Doré Entrée par le 8, 75003 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75003\", \"subdivision\": \"IDF\"}",
"phone": "+33 1 42 78 93 75",
"website": "https://www.citizenconceptstore.com",
"hours": "Lun-Sam 11 AM–7 PM",
"category": "Dépôt-vente Luxe",
"desc_fr": "Citizen Concept Store est un dépôt-vente vintage et luxe du Marais ouvert 7j/7, proposant des pièces contemporaines et vintage de grandes maisons dans un espace de 300m².",
"desc_en": "Citizen Concept Store is a vintage and luxury consignment boutique in the Marais open 7 days a week, offering contemporary and vintage pieces from major houses in a 300m² space.",
"lat": 48.8602293,
"lon": 2.3638994,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAwerWiryQTnLbv2yu0LX6qnDsxdPsQEeDWBjo3IREelpGhpVqvJyLcNP1sp2vHzhAvBSDInkdGGAHireQyQxFW-vBi-Q4cjfAFRN1Igj8vrLJi9cyzNlWzJnv5LT6-pX4zig5xww=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAwerWiryQTnLbv2yu0LX6qnDsxdPsQEeDWBjo3IREelpGhpVqvJyLcNP1sp2vHzhAvBSDInkdGGAHireQyQxFW-vBi-Q4cjfAFRN1Igj8vrLJi9cyzNlWzJnv5LT6-pX4zig5xww=w800-h600-k-no"
],
"status": "published"
},
{
"id": "comptoir-vintage-vintage-shop-paris",
"name": "Comptoir Vintage - Vintage Shop Paris",
"badge": "Mode Vintage · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8626505, \"longitude\": 2.3648225}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"104\", \"name\": \"Rue de Turenne\", \"apt\": \"\"}, \"formatted\": \"104 Rue de Turenne, 75003 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75003\", \"subdivision\": \"IDF\"}",
"phone": "+33 6 24 28 52 50",
"website": "https://www.comptoirvintage.com",
"hours": "Lun-Sam 11 AM–7 PM",
"category": "Mode Vintage",
"desc_fr": "Comptoir Vintage est une boutique vintage 5 étoiles du Marais proposant une curation irréprochable de pièces rares des années 60 aux années 2000. Noté 5/5 avec 83 avis.",
"desc_en": "Comptoir Vintage is a 5-star vintage boutique in the Marais offering an impeccable curation of rare pieces from the 1960s to the 2000s. Rated 5/5 with 83 reviews.",
"lat": 48.8626505,
"lon": 2.3648225,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAweqPqHrONJcZvvU8CZgzXG8Jwkh985kTQ_sAZlmNCkHHxgnYrdWF__-0WeMkkCZXI38sWtF2Ok6D6Fnl3zn43GziacoROq_-rgR_elO5RdH30JPNaCJadJPnxwrU3ifhmyveegHWbA=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAweqPqHrONJcZvvU8CZgzXG8Jwkh985kTQ_sAZlmNCkHHxgnYrdWF__-0WeMkkCZXI38sWtF2Ok6D6Fnl3zn43GziacoROq_-rgR_elO5RdH30JPNaCJadJPnxwrU3ifhmyveegHWbA=w800-h600-k-no"
],
"status": "published"
},
{
"id": "faure-le-page",
"name": "Fauré Le Page",
"badge": "Maroquinerie · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8677538, \"longitude\": 2.3263699}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"21\", \"name\": \"Rue Cambon\", \"apt\": \"\"}, \"formatted\": \"21 Rue Cambon, 75001 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75001\", \"subdivision\": \"IDF\"}",
"phone": "+33 1 49 27 99 36",
"website": "https://faurelepage.com",
"hours": "Lun-Sam 10:30 AM–7 PM",
"category": "Maroquinerie",
"desc_fr": "Maison fondée à Paris en 1717, Fauré Le Page est l'une des plus anciennes maisons de maroquinerie au monde. Sa boutique rue Cambon perpétue 300 ans d'excellence artisanale avec ses canvas iconiques.",
"desc_en": "Founded in Paris in 1717, Fauré Le Page is one of the world's oldest luxury leather goods houses, perpetuating 300 years of artisanal excellence with its iconic canvas designs.",
"lat": 48.8677538,
"lon": 2.3263699,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAweqClUiag-UmHtP1ve4MVng11B0jGYC9OXt54y0R9HHm5xfqEc1s4JKFdJNjJFhMEY7ULsDXIfCuE8FR02J180BjwZ1pRMmXPkVOOEY1WKFbib1f9RUgI52vWAj5iQvJZRp4uTqf24nJOt1v=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAweqClUiag-UmHtP1ve4MVng11B0jGYC9OXt54y0R9HHm5xfqEc1s4JKFdJNjJFhMEY7ULsDXIfCuE8FR02J180BjwZ1pRMmXPkVOOEY1WKFbib1f9RUgI52vWAj5iQvJZRp4uTqf24nJOt1v=w800-h600-k-no"
],
"status": "published"
},
{
"id": "boutique-cresus-paris-a-maty-opera",
"name": "Boutique CRESUS - Paris à MATY Opera",
"badge": "Horlogerie & Bijoux · Paris",
"city": "Paris",
"country": "France",
"region": "europe",
"address": "{\"city\": \"Paris\", \"location\": {\"latitude\": 48.8705329, \"longitude\": 2.3327926}, \"countryFullname\": \"France\", \"streetAddress\": {\"number\": \"4\", \"name\": \"Pl. de l'Opéra\", \"apt\": \"\"}, \"formatted\": \"4 Pl. de l'Opéra, 75002 Paris, France\", \"country\": \"FR\", \"postalCode\": \"75002\", \"subdivision\": \"IDF\"}",
"phone": "+33 1 40 20 16 84",
"website": "https://www.cresus.fr/boutique-montres-bijoux-paris-opera",
"hours": "Lun-Sam 10 AM–7:30 PM",
"category": "Horlogerie & Bijoux",
"desc_fr": "Crésus est un horloger-joaillier de seconde main de luxe installé Place de l'Opéra. Montres et bijoux Rolex, Cartier et Patek Philippe soigneusement expertisés depuis plus de 20 ans.",
"desc_en": "Crésus is a luxury second-hand watch and jewellery specialist at Place de l'Opéra, offering carefully authenticated Rolex, Cartier and Patek Philippe pieces for over 20 years.",
"lat": 48.8705329,
"lon": 2.3327926,
"main_photo": "https://lh3.googleusercontent.com/gps-cs-s/AHVAweog1U-Kd8FqIozv-aQobVd_ZpSviuLtysEEIl8AtC3nzZAImOZGLZIZtofgYRxivQGe5qQUr8XucqI9CTjXXvJng4m6RTDtp_XnSfYU0hH1g8KwB8Ri56pM8QoDdsnx_sFVptfW9po15j7u=w800-h600-k-no",
"photos": [
"https://lh3.googleusercontent.com/gps-cs-s/AHVAweog1U-Kd8FqIozv-aQobVd_ZpSviuLtysEEIl8AtC3nzZAImOZGLZIZtofgYRxivQGe5qQUr8XucqI9CTjXXvJng4m6RTDtp_XnSfYU0hH1g8KwB8Ri56pM8QoDdsnx_sFVptfW9po15j7u=w800-h600-k-no"
],
"status": "published"
}
];

// Index par ID
const DB_IDX = {};
DB.forEach(b => DB_IDX[b.id] = b);

// ── FONCTIONS ──
async function loadBoutiques() {
  return DB.filter(b => b.status === 'published');
}

async function loadBoutique(id) {
  return DB_IDX[id] || null;
}

async function loadBoutiquesByCity(city) {
  return DB.filter(b => b.city === city);
}

async function loadBoutiquesByRegion(region) {
  return DB.filter(b => b.region === region);
}
